; Note: lines starting with semicolon are for comments.
; Load plugins for any title.

[default]
/data/GoldHEN/plugins/game_patch.prx

; Load plugins only for Beat Saber.

[CUSA12878]
/data/GoldHEN/plugins/beat_saber_deluxe.prx

; Load plugins only for Playroom.

[CUSA00001]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx
